## Это конфигурационный файл для системы заданий.
## Он будет включен только при включенном флаге конфигурации LOAD_JOBS_FROM_TXT.
## Мы используем здесь систему ключей, которые напрямую связаны с заданием, просто чтобы убедиться, что они не будут десинхронизированы, если мы решим изменить название задания.
## В этом файле вы можете изменить (на данный момент) пять (шесть, если задание является командной головкой) различных переменных.
## Total Positions - это количество рабочих мест за смену, Spawn Positions - это количество мест, загружаемых при спавне. Если вы установите значение -1, то это неограниченно.
## Требования к игровому времени указываются в минутах, и задание будет разблокировано, когда игрок достигнет этого количества времени.
## Однако это может быть заменено требуемым возрастом аккаунта, который представляет собой время в днях, в течение которого вы должны иметь аккаунт на сервере.
## Также существует требуемый возраст персонажа в годах. Он не позволяет игроку присоединиться к этой профессии, если возраст его персонажа меньше требуемого. Установка значения 0 означает, что оно отключено для этой профессии.
## Наконец, есть настройка «Белый список» человеческой власти. Вы можете установить либо «HUMANS_ONLY», либо «NON_HUMANS_ALLOWED». Проверьте настройку «Human Authority» в файле game_options, чтобы узнать, какой вариант вам следует выбрать. Обратите внимание, что эта запись появляется только на тех заданиях, которые отмечены как главы персонала.

## Со временем в этот файл могут быть добавлены дополнительные параметры конфигурации.
## Вы можете использовать глагол администратора 'Generate Job Configuration' в игре, чтобы автоматически генерировать этот конфиг как загружаемый файл без необходимости вручную редактировать этот файл, если мы добавим больше заданий или больше вещей, которые вы можете редактировать здесь.
## Он всегда будет уважать ранее существовавшие значения в конфиге, но будет соответствующим образом добавлять дополнительные поля, когда они генерируются.
## Настоятельно рекомендуется создать собственную версию этого файла, а не использовать ту, что размещена в кодовой базе.

## Игра не будет читать строки, которые закомментированы символом '#', чтобы позволить вам отступить от умолчаний кодовой базы.
## Если вы хотите отменить значения кодовой базы, добавьте значение, а затем откомментируйте эту строку, убрав # из имени ключа задания.
## Убедитесь, что ключ пропущен, не вводите пробелы при разкомментировании ключа. Например:
## «# Всего позиций» всегда должно быть заменено на «Всего позиций», без дополнительных пробелов.
## Удачи в редактировании!

[AI]
"# Playtime Requirements" = 180
"# Required Account Age" = 30
"# Required Character Age" = 0
"# Spawn Positions" = 1
"# Total Positions" = 1

[ASSISTANT]
"# Playtime Requirements" = 0
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = -1
"# Total Positions" = -1

[ATMOSPHERIC_TECHNICIAN]
"# Playtime Requirements" = 60
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 2
"# Total Positions" = 3

[BARTENDER]
"# Playtime Requirements" = 0
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 1
"# Total Positions" = 1

[BITRUNNER]
"# Playtime Requirements" = 0
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 3
"# Total Positions" = 3

[BOTANIST]
"# Playtime Requirements" = 0
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 2
"# Total Positions" = 3

[CAPTAIN]
"# Human Authority Whitelist Setting" = "HUMANS_ONLY"
"# Playtime Requirements" = 180
"# Required Account Age" = 14
"# Required Character Age" = 0
"# Spawn Positions" = 1
"# Total Positions" = 1

[CARGO_TECHNICIAN]
"# Playtime Requirements" = 0
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 3
"# Total Positions" = 5

[CHAPLAIN]
"# Playtime Requirements" = 0
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 1
"# Total Positions" = 1

[CHEMIST]
"# Playtime Requirements" = 60
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 2
"# Total Positions" = 2

[CHIEF_ENGINEER]
"# Human Authority Whitelist Setting" = "HUMANS_ONLY"
"# Playtime Requirements" = 180
"# Required Account Age" = 7
"# Required Character Age" = 0
"# Spawn Positions" = 1
"# Total Positions" = 1

[CHIEF_MEDICAL_OFFICER]
"# Human Authority Whitelist Setting" = "HUMANS_ONLY"
"# Playtime Requirements" = 180
"# Required Account Age" = 7
"# Required Character Age" = 0
"# Spawn Positions" = 1
"# Total Positions" = 1

[CLOWN]
"# Playtime Requirements" = 0
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 1
"# Total Positions" = 1

[COOK]
"# Playtime Requirements" = 0
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 1
"# Total Positions" = 2

[CORONER]
"# Playtime Requirements" = 0
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 1
"# Total Positions" = 1

[CURATOR]
"# Playtime Requirements" = 0
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 1
"# Total Positions" = 1

[CYBORG]
"# Playtime Requirements" = 120
"# Required Account Age" = 21
"# Required Character Age" = 0
"# Spawn Positions" = 3
"# Total Positions" = 0

[DETECTIVE]
"# Playtime Requirements" = 300
"# Required Account Age" = 7
"# Required Character Age" = 0
"# Spawn Positions" = 1
"# Total Positions" = 1

[GENETICIST]
"# Playtime Requirements" = 60
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 2
"# Total Positions" = 2

[HEAD_OF_PERSONNEL]
"# Human Authority Whitelist Setting" = "HUMANS_ONLY"
"# Playtime Requirements" = 180
"# Required Account Age" = 10
"# Required Character Age" = 0
"# Spawn Positions" = 1
"# Total Positions" = 1

[HEAD_OF_SECURITY]
"# Human Authority Whitelist Setting" = "HUMANS_ONLY"
"# Playtime Requirements" = 300
"# Required Account Age" = 14
"# Required Character Age" = 0
"# Spawn Positions" = 1
"# Total Positions" = 1

[JANITOR]
"# Playtime Requirements" = 0
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 1
"# Total Positions" = 2

[LAWYER]
"# Playtime Requirements" = 0
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 2
"# Total Positions" = 2

[MEDICAL_DOCTOR]
"# Playtime Requirements" = 0
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 4
"# Total Positions" = 6

[MIME]
"# Playtime Requirements" = 0
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 1
"# Total Positions" = 1

[PARAMEDIC]
"# Playtime Requirements" = 0
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 2
"# Total Positions" = 2

[PRISONER]
"# Playtime Requirements" = 0
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 2
"# Total Positions" = 0

[PSYCHOLOGIST]
"# Playtime Requirements" = 0
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 1
"# Total Positions" = 1

[QUARTERMASTER]
"# Human Authority Whitelist Setting" = "NON_HUMANS_ALLOWED"
"# Playtime Requirements" = 0
"# Required Account Age" = 7
"# Required Character Age" = 0
"# Spawn Positions" = 1
"# Total Positions" = 1

[RESEARCH_DIRECTOR]
"# Human Authority Whitelist Setting" = "HUMANS_ONLY"
"# Playtime Requirements" = 180
"# Required Account Age" = 7
"# Required Character Age" = 0
"# Spawn Positions" = 1
"# Total Positions" = 1

[ROBOTICIST]
"# Playtime Requirements" = 60
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 2
"# Total Positions" = 2

[SCIENTIST]
"# Playtime Requirements" = 60
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 3
"# Total Positions" = 5

[SECURITY_OFFICER]
"# Playtime Requirements" = 300
"# Required Account Age" = 7
"# Required Character Age" = 0
"# Spawn Positions" = 5
"# Total Positions" = 5

[SHAFT_MINER]
"# Playtime Requirements" = 0
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 3
"# Total Positions" = 3

[STATION_ENGINEER]
"# Playtime Requirements" = 60
"# Required Account Age" = 0
"# Required Character Age" = 0
"# Spawn Positions" = 5
"# Total Positions" = 5

[VETERAN_ADVISOR]
"# Playtime Requirements" = 6000
"# Required Account Age" = 7
"# Required Character Age" = 0
"# Spawn Positions" = 0
"# Total Positions" = 0

[WARDEN]
"# Playtime Requirements" = 300
"# Required Account Age" = 7
"# Required Character Age" = 0
"# Spawn Positions" = 1
"# Total Positions" = 1
